filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "filebeat_internal"
  password: "your_password"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info

strict.perms: false  # Desativa verificação de permissões

