global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kubernetes'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9100']

rule_files:
  - "alert.rules.yml"